name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn
          yarn upgrade
      - name: Run Unit Tests
        run: |
          yarn test
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.node-version }}
          parallel: true
        run: |
          coveralls --service=github
